INFO  2022-07-27 19:03:48,649 minitest.py _miniSetUp      241 =========Current case: test_03_pre_cancel=========
INFO  2022-07-27 19:03:48,650 minitest.py _miniSetUp      242 package info: E:.PycharmProjects.hj_xcx.case.test_order, case info: TestOrder.test_03_pre_cancel
INFO  2022-07-27 19:03:48,650 basenative.py wrapper         22  call BaseNative.back_to_miniprogram
INFO  2022-07-27 19:03:48,651 basenative.py back_to_miniprogram 476 try back_to_miniprogram 3
INFO  2022-07-27 19:03:48,652 basenative.py wrapper         26  call BaseNative.back_to_miniprogram end
INFO  2022-07-27 19:03:48,653 app.py     relaunch        297 ReLaunch: /pages/loadPage/index
INFO  2022-07-27 19:03:49,038 app.py     _on_route_changed 443 Route changed, {'name': 'onAppRouteDone', 'args': [{'webviewId': 21, 'path': 'pages/loadPage/index', 'query': {}, 'openType': 'reLaunch'}, 1658919829010]}
INFO  2022-07-27 19:03:49,040 minitest.py capture         523 capture setup.png
INFO  2022-07-27 19:03:49,041 basenative.py wrapper         22  call IdeNative.screen_shot
INFO  2022-07-27 19:03:49,106 basenative.py wrapper         26  call IdeNative.screen_shot end
INFO  2022-07-27 19:03:49,653 app.py     _on_route_changed 443 Route changed, {'name': 'onAppRouteDone', 'args': [{'webviewId': 22, 'path': 'pages/home/index', 'query': {}, 'openType': 'reLaunch'}, 1658919829627]}
ERROR 2022-07-27 19:03:52,346 connection.py _on_error       265 [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO  2022-07-27 19:03:52,348 connection.py _ws_run_forever 151 websocket run forever shutdown
INFO  2022-07-27 19:03:54,116 basenative.py wrapper         22  call BaseNative.get_start_up
INFO  2022-07-27 19:03:54,118 basenative.py wrapper         26  call BaseNative.get_start_up end
INFO  2022-07-27 19:03:54,119 minitest.py capture         523 capture teardown.png
INFO  2022-07-27 19:03:54,120 basenative.py wrapper         22  call IdeNative.screen_shot
INFO  2022-07-27 19:03:54,120 minitest.py capture         523 capture teardown.png
INFO  2022-07-27 19:03:54,121 basenative.py wrapper         22  call IdeNative.screen_shot
ERROR 2022-07-27 19:03:54,121 minitest.py _miniTearDown   482 Connection is already closed.
Traceback (most recent call last):
  File "e:\software\python\lib\site-packages\minium\framework\minitest.py", line 476, in _miniTearDown
    retry(2)(self.capture)("teardown")
  File "e:\software\python\lib\site-packages\minium\utils\utils.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\framework\minitest.py", line 524, in capture
    self.native.screen_shot(path)
  File "e:\software\python\lib\site-packages\minium\native\wx_native\basenative.py", line 23, in wrapper
    result = func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\native\wx_native\idenative.py", line 28, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\app.py", line 128, in screen_shot
    b64_data = self.connection.send("App.captureScreenshot").get("result").get("data")
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 184, in send
    self._send(message)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 154, in _send
    return self._client.send(message)
  File "e:\software\python\lib\site-packages\websocket\_app.py", line 204, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR 2022-07-27 19:03:54,161 assertbase.py _teardown_collect 271 <bound method TestOrder.test_03_pre_cancel of <case.test_order.TestOrder testMethod=test_03_pre_cancel>>
Traceback (most recent call last):
  File "e:\software\python\lib\site-packages\minium\framework\libs\unittest\case.py", line 29, in testPartExecutor
    yield
  File "e:\software\python\lib\site-packages\minium\framework\libs\unittest\case.py", line 110, in run
    self._callTestMethod(testMethod)
  File "e:\software\python\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "E:\PycharmProjects\hj_xcx\case\test_order.py", line 56, in test_03_pre_cancel
    HomePage(self.page).click_my()
  File "e:\software\python\lib\site-packages\minium\framework\assertbase.py", line 333, in __getattribute__
    attr = super().__getattribute__(item)
  File "e:\software\python\lib\site-packages\minium\framework\minitest.py", line 490, in page
    return self.mini.app.get_current_page()
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\app.py", line 225, in get_current_page
    ret = get_current_page()
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\app.py", line 217, in get_current_page
    ret = self.connection.send("App.getCurrentPage")
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 184, in send
    self._send(message)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 154, in _send
    return self._client.send(message)
  File "e:\software\python\lib\site-packages\websocket\_app.py", line 204, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
